name: amazon-photo/locality/natpe/improved
root: ./configs
dataset: dataset_configs/amazon-photo/locality/standard_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/natpe/improved_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/natpe/experiment_config.yaml
