name: coauthor-physics/locality/gpn/standard
root: ./configs
dataset: dataset_configs/coauthor-physics/locality/standard_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/gpn/standard_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/gpn/experiment_config.yaml
