name: ogbn-products/locality/mpn/standard-trivial
root: ./configs
dataset: dataset_configs/ogbn-products/locality/standard_dataset_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/mpn/standard_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/mpn/experiment_config.yaml
