do_train: True
train_stage:
  stage_name: train
  
  num_splits: 1
  num_inits: 5

  save_separate_results: False
  save_history_results: False

do_infer: True
infer_stage:
  stage_name: infer

  num_splits: 1
  num_inits: 5

  save_separate_results: True
  save_history_results: True