datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/cora-ml/feature/dataset_config.yaml
experiment: experiment_configs/natpn/experiment_config.yaml
method: method_configs/natpn/method_config.yaml
name: cora-ml/feature/natpn
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
