datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/coauthor-physics/feature/dataset_config.yaml
experiment: experiment_configs/mlp/experiment_config.yaml
method: method_configs/mlp/method_config.yaml
name: coauthor-physics/feature/mlp
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
