name: amazon-computer/density/gpe/standard
root: ./configs
dataset: dataset_configs/amazon-computer/density/standard_dataset_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/gpe/standard_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/gpe/experiment_config.yaml
