datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/citeseer_pagerank_dataset_config.yaml
experiment: experiment_configs/base_natgpn_experiment_config.yaml
method: method_configs/base_natgpn_method_config.yaml
name: citeseer/pagerank/natgpn
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
