train_routine:

  train_module:
    class_name: default_mpn

    optimizer_config:
      lr: 0.0003
      weight_decay: 0.00001

    model_config:
      encoder_config:
        feature_dims:
        - 64
        - 64
        layer_config:
          dropout: 0.0
          activation_name: tanh
          activation_args: {}
          layer_name: conv:sage
          layer_args:
            aggregator_type: mean
        final: False

      classifier_config:
        feature_dims:
        - 64
        - 64
        layer_config:
          dropout: 0.0
          activation_name: tanh
          activation_args: {}
          layer_name: fc:linear
          layer_args: {}
        final: True
      
    metrics_config:
      classification_basic:
        metric_names:
          - accuracy
        metric_args:
          num_classes:
          average: micro

      classification_ranking:
        metric_names:
          - auroc
          - ap
        metric_args:
          num_classes:
          average: macro

      misclassification_detection_using_data:
        metric_names:
          - prr
        metric_args: {}

      misclassification_detection_using_knowledge:
        metric_names:
          - prr
        metric_args: {}

      misclassification_detection_using_total:
        metric_names:
          - prr
        metric_args: {}

      ood_detection_using_data:
        metric_names:
          - auroc
          - ap
        metric_args: {}

      ood_detection_using_knowledge:
        metric_names:
          - auroc
          - ap
        metric_args: {}

      ood_detection_using_total:
        metric_names:
          - auroc
          - ap
        metric_args: {}

      aggregated_performance_using_data:
        metric_names:
          - auprc
        metric_args: {}

      aggregated_performance_using_knowledge:
        metric_names:
          - auprc
        metric_args: {}

      aggregated_performance_using_total:
        metric_names:
          - auprc
        metric_args: {}


infer_routine:

  eval_module:

  infer_module: