datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/citeseer_random_dataset_config.yaml
experiment: experiment_configs/base_gpn_experiment_config.yaml
method: method_configs/base_gpn_method_config.yaml
name: citeseer/random/gpn
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
