name: amazon-ratings/pagerank/natpe/sanity
root: ./configs
dataset: dataset_configs/amazon-ratings/pagerank/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/natpe/sanity_method_config.yaml
trainer: trainer_configs/beta_trainer_config.yaml
experiment: experiment_configs/natpe/experiment_config.yaml
