datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/pubmed/personalised/dataset_config.yaml
experiment: experiment_configs/natgpn/experiment_config.yaml
method: method_configs/natgpn/method_config.yaml
name: pubmed/personalised/natgpn
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
