datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/pubmed/feature/dataset_config.yaml
experiment: experiment_configs/gpm/experiment_config.yaml
method: method_configs/gpm/method_config.yaml
name: pubmed/feature/gpm
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
