datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/coauthor-cs/feature/dataset_config.yaml
experiment: experiment_configs/natpe/experiment_config.yaml
method: method_configs/natpe/method_config.yaml
name: coauthor-cs/feature/natpe
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
