datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/citeseer_personalised_dataset_config.yaml
experiment: experiment_configs/base_pn_experiment_config.yaml
method: method_configs/base_pn_method_config.yaml
name: citeseer/personalised/pn
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
