datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/cora-ml_random_dataset_config.yaml
experiment: experiment_configs/base_gen_experiment_config.yaml
method: method_configs/base_gen_method_config.yaml
name: cora-ml/random/gen
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
