datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/coauthor-physics_random_dataset_config.yaml
experiment: experiment_configs/base_mlp_experiment_config.yaml
method: method_configs/base_mlp_method_config.yaml
name: coauthor-physics/random/mlp
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
