name: amazon-photo/random/pn/sanity
root: ./configs
dataset: dataset_configs/amazon-photo/random/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/pn/sanity_method_config.yaml
trainer: trainer_configs/alpha_trainer_config.yaml
experiment: experiment_configs/pn/experiment_config.yaml
