datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/amazon-photo/random/dataset_config.yaml
experiment: experiment_configs/gpn/experiment_config.yaml
method: method_configs/gpn/method_config.yaml
name: amazon-photo/random/gpn
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
