datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/coauthor-physics_feature_dataset_config.yaml
experiment: experiment_configs/base_natpn_experiment_config.yaml
method: method_configs/base_natpn_method_config.yaml
name: coauthor-physics/feature/natpn
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
