name: amazon-computer/clustering/gpm/sanity
root: ./configs
dataset: dataset_configs/amazon-computer/clustering/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/gpm/sanity_method_config.yaml
trainer: trainer_configs/alpha_trainer_config.yaml
experiment: experiment_configs/gpm/experiment_config.yaml
