name: questions/pagerank/en/sanity
root: ./configs
dataset: dataset_configs/questions/pagerank/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/en/sanity_method_config.yaml
trainer: trainer_configs/alpha_trainer_config.yaml
experiment: experiment_configs/en/experiment_config.yaml
