name: coauthor-cs/popularity/natpe/standard
root: ./configs
dataset: dataset_configs/coauthor-cs/popularity/standard_dataset_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/natpe/standard_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/natpe/experiment_config.yaml
