name: questions/clustering/natpn/sanity
root: ./configs
dataset: dataset_configs/questions/clustering/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/natpn/sanity_method_config.yaml
trainer: trainer_configs/beta_trainer_config.yaml
experiment: experiment_configs/natpn/experiment_config.yaml
