datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/amazon-computer/random/dataset_config.yaml
experiment: experiment_configs/mpe/experiment_config.yaml
method: method_configs/mpe/method_config.yaml
name: amazon-computer/random/mpe
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
