name: pubmed/popularity/mpe/improved
root: ./configs
dataset: dataset_configs/pubmed/popularity/standard_dataset_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/mpe/improved_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/mpe/experiment_config.yaml
