do_train: True
train_stage:
  stage_name: train

  num_splits: 1
  num_inits: 5

  save_separate_results: False
  save_history_results: False

do_infer: True
infer_stage:
  stage_name: infer
  
  num_splits: 1
  num_inits: 1                    # this should always be 1, since ensembling over all instances is performed, and technically there is no averaging over inits

  save_separate_results: False
  save_history_results: True