name: citeseer/locality/natpn/standard
root: ./configs
dataset: dataset_configs/citeseer/locality/standard_dataset_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/natpn/standard_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/natpn/experiment_config.yaml
