name: amazon-computer/random/natpm/sanity
root: ./configs
dataset: dataset_configs/amazon-computer/random/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/natpm/sanity_method_config.yaml
trainer: trainer_configs/alpha_trainer_config.yaml
experiment: experiment_configs/natpm/experiment_config.yaml
