name: cora-ml/clustering/gpn/sanity
root: ./configs
dataset: dataset_configs/cora-ml/clustering/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/gpn/sanity_method_config.yaml
trainer: trainer_configs/alpha_trainer_config.yaml
experiment: experiment_configs/gpn/experiment_config.yaml
