name: citeseer/personalised/gpe/sanity
root: ./configs
dataset: dataset_configs/citeseer/personalised/sanity_dataset_config.yaml
sampler: sampler_configs/none_sampler_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/gpe/sanity_method_config.yaml
trainer: trainer_configs/alpha_trainer_config.yaml
experiment: experiment_configs/gpe/experiment_config.yaml
