datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/cora-ml/feature/dataset_config.yaml
experiment: experiment_configs/gpe/experiment_config.yaml
method: method_configs/gpe/method_config.yaml
name: cora-ml/feature/gpe
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
