datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/amazon-photo/personalised/dataset_config.yaml
experiment: experiment_configs/en/experiment_config.yaml
method: method_configs/en/method_config.yaml
name: amazon-photo/personalised/en
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
