datamodule: datamodule_configs/standard_datamodule_config.yaml
dataset: dataset_configs/amazon-photo_random_dataset_config.yaml
experiment: experiment_configs/base_gpe_experiment_config.yaml
method: method_configs/base_gpe_method_config.yaml
name: amazon-photo/random/gpe
root: ./configs
sampler: sampler_configs/none_sampler_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
