name: coauthor-physics/density/gpn/improved
root: ./configs
dataset: dataset_configs/coauthor-physics/density/standard_dataset_config.yaml
datamodule: datamodule_configs/standard_datamodule_config.yaml
method: method_configs/gpn/improved_method_config.yaml
trainer: trainer_configs/standard_trainer_config.yaml
experiment: experiment_configs/gpn/experiment_config.yaml
